embeddings_database_path = r"D:\PyTorch\FaceRecognition\Data\RecognitionResources/face_scrub_embeddings.pkl"
actor_distance_thresholds_path = r"D:\PyTorch\FaceRecognition\Data\RecognitionResources/actor_distance_thresholds.json"
index_path = r"D:\PyTorch\FaceRecognition\Data\RecognitionResources/actor_subcentroids.index"
actor_map_path = r"D:\PyTorch\FaceRecognition\Data\RecognitionResources/actor_map.pkl"
ukr_actor_names_path = r"D:\PyTorch\FaceRecognition\Data\RecognitionResources/actor_map_ukr.json"
